GET http://20.76.200.232/jobs/

### 

GET http://20.76.200.232/jobs?status=Completed

### 

GET http://20.76.200.232/jobs?status=Cancelled

### 

GET http://20.76.200.232/jobs?status=Running

### 

GET http://20.76.200.232/jobs/44356951-b759-4bf7-92fd-ea399f087886/


####

POST https://localhost:44324/jobs
content-type: application/json

{
    "Query": "DeviceId IN ['FPde3bee3fadb7440abca0513cc51221dd']",
    "Data":" {\r\n        \"key1\": \"value2\"\r\n    }",
    "Type": "DirectMethod"
}

### 

POST http://localhost:49154/jobs
content-type: application/json

{
    "Query": "tags.gatewayspecs.groups=['DIFieldTest']",
    "Data":"{ \"DesiredProperties\":{ \r\n    \"firmwareVersion\": \"2.11.2\" \r\n    } \r\n}",
    "Type": "UpdateDeviceTwin"
}

### 

DELETE  https://localhost:44324/jobs/d3d90082-ed0e-4206-8016-f0040567b8a3