GET https://localhost:44324/jobs/

### 

GET https://localhost:44324/jobs?status=Cancelled

### 

GET https://localhost:44324/jobs?status=Running

### 

GET https://localhost:44324/jobs/12345556/


####

POST https://localhost:44324/jobs
content-type: application/json

{
    "Query": "DeviceId IN ['FPde3bee3fadb7440abca0513cc51221dd']",
    "Data":" {\r\n        \"key1\": \"value2\"\r\n    }",
    "Type": "DirectMethod"
}

### 

POST https://localhost:44324/jobs
content-type: application/json

{
    "Query": "DeviceId IN ['FPde3bee3fadb7440abca0513cc51221dd']",
    "Data":"{ Tags:{\r\n\"FieldTest\": \"true\"\r\n}, DesiredProperties:{\r\n\"FeatureFlagDI\": \"true\" } }",
    "Type": "UpdateDeviceTwin"
}

### 

DELETE  https://localhost:44324/jobs/d3d90082-ed0e-4206-8016-f0040567b8a3